import json

notebook = {
    'cells': [
        {
            'cell_type': 'markdown',
            'metadata': {},
            'source': [
                '# Phase 9: Standard-MLP Swin-MoE Kaggle Experiment\n',
                '\n',
                'This notebook trains the Phase 9 `swin_standard_moe` model and evaluates it zero-shot.'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# ==========================================\n',
                '# STEP 1: ENVIRONMENT SETUP\n',
                '# ==========================================\n',
                'import os\n',
                'import sys\n',
                'import shutil\n',
                '\n',
                '# Delete old repo to ensure fresh code\n',
                '!rm -rf vision_transformer_research\n',
                '!git clone https://github.com/toqeer-ahmed/vision_tranformer_moe.git vision_transformer_research\n',
                'os.chdir(\'vision_transformer_research\')\n',
                'sys.path.append(os.path.abspath(\'.\'))\n',
                '\n',
                '!pip install -r requirements.txt -q'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# ==========================================\n',
                '# STEP 2: RESTRUCTURE DATASETS (SUPER BULLETPROOF)\n',
                '# ==========================================\n',
                'print("Setting up dataset paths...")\n',
                'os.makedirs("data/medical_dataset/images", exist_ok=True)\n',
                'os.makedirs("data/medical_dataset/masks", exist_ok=True)\n',
                'os.makedirs("data/busbra_dataset/images", exist_ok=True)\n',
                'os.makedirs("data/busbra_dataset/masks", exist_ok=True)\n',
                '\n',
                '# Kaggle sometimes uses symlinks for datasets, so we must set followlinks=True\n',
                '# We search the entire /kaggle/input directory to avoid any folder name mismatches.\n',
                'for root_dir, _, files in os.walk("/kaggle/input", followlinks=True):\n',
                '    for file in files:\n',
                '        if file.lower().endswith((".png", ".jpg", ".jpeg", ".bmp")):\n',
                '            src = os.path.join(root_dir, file)\n',
                '            \n',
                '            # Categorize as BUSI\n',
                '            if "busi" in src.lower() and "checkpoints" not in src.lower():\n',
                '                if "_mask" in file.lower():\n',
                '                    shutil.copy(src, os.path.join("data/medical_dataset/masks", file))\n',
                '                else:\n',
                '                    shutil.copy(src, os.path.join("data/medical_dataset/images", file))\n',
                '                    \n',
                '            # Categorize as BUSBRA\n',
                '            elif "busbra" in src.lower():\n',
                '                if "mask" in src.lower():\n',
                '                    shutil.copy(src, os.path.join("data/busbra_dataset/masks", file))\n',
                '                else:\n',
                '                    shutil.copy(src, os.path.join("data/busbra_dataset/images", file))\n',
                '\n',
                'print(f"Total BUSI images: {len(os.listdir(\'data/medical_dataset/images\'))}")\n',
                'print(f"Total BUSI masks: {len(os.listdir(\'data/medical_dataset/masks\'))}")\n',
                'print(f"Total BUSBRA images: {len(os.listdir(\'data/busbra_dataset/images\'))}")\n',
                'print(f"Total BUSBRA masks: {len(os.listdir(\'data/busbra_dataset/masks\'))}")'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# ==========================================\n',
                '# STEP 3: CONFIGURE EXPERIMENT\n',
                '# ==========================================\n',
                'config_yaml = """\\\n',
                'model:\n',
                '  name: "swin_standard_moe"\n',
                '  backbone: "microsoft/swin-tiny-patch4-window7-224"\n',
                '  num_classes: 3\n',
                '\n',
                'moe:\n',
                '  num_experts: 4\n',
                '  top_k: 2\n',
                '  noisy_gating: true\n',
                '  balance_loss_coef: 0.01\n',
                '  warm_init: true\n',
                '\n',
                'training:\n',
                '  batch_size: 32\n',
                '  learning_rate: 0.0001\n',
                '  weight_decay: 0.01\n',
                '  num_epochs: 50\n',
                '  early_stopping_patience: 10\n',
                '  img_size: 224\n',
                '  seed: 42\n',
                '"""\n',
                'os.makedirs("configs", exist_ok=True)\n',
                'with open("configs/swin_standard_moe_kaggle.yaml", "w") as f:\n',
                '    f.write(config_yaml)\n',
                'print("Configuration saved.")'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# ==========================================\n',
                '# STEP 4: FULL TRAINING\n',
                '# ==========================================\n',
                'print("Starting Full Training...")\n',
                '!python training/train_swin_standard_moe.py --config configs/swin_standard_moe_kaggle.yaml --warm-init'
            ]
        },
        {
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': [],
            'source': [
                '# ==========================================\n',
                '# STEP 5: ZERO-SHOT EVALUATION ON BUS-BRA\n',
                '# ==========================================\n',
                'import torch\n',
                'import yaml\n',
                'import glob\n',
                'import json\n',
                'from models.swin import SwinSegmentation, replace_swin_ffn_with_standard_moe\n',
                'from datasets.medical_dataset import get_medical_dataloaders\n',
                'from evaluation.metrics import SegmentationMetricAccumulator\n',
                '\n',
                '# Find the best checkpoint from the training run\n',
                'ckpt_paths = glob.glob("outputs/swin_standard_moe_*/checkpoints/best_model.pth")\n',
                'if not ckpt_paths:\n',
                '    print("Error: Could not find trained checkpoint!")\n',
                'else:\n',
                '    best_ckpt = ckpt_paths[-1]\n',
                '    print(f"Evaluating checkpoint: {best_ckpt}")\n',
                '    \n',
                '    # Load config and model\n',
                '    with open("configs/swin_standard_moe_kaggle.yaml", "r") as f:\n',
                '        config = yaml.safe_load(f)\n',
                '    \n',
                '    model = SwinSegmentation(num_classes=3, pretrained=False)\n',
                '    replace_swin_ffn_with_standard_moe(model, config["moe"])\n',
                '    \n',
                '    checkpoint = torch.load(best_ckpt, map_location="cuda")\n',
                '    if "state_dict" in checkpoint:\n',
                '        model.load_state_dict(checkpoint["state_dict"], strict=False)\n',
                '    elif "model_state_dict" in checkpoint:\n',
                '        model.load_state_dict(checkpoint["model_state_dict"], strict=False)\n',
                '    else:\n',
                '        model.load_state_dict(checkpoint, strict=False)\n',
                '    \n',
                '    model = model.cuda()\n',
                '    model.eval()\n',
                '    \n',
                '    # Load BUSBRA Zero-Shot dataset. BUSBRA doesn\'t have train/val split in our dataloader out of the box, \n',
                '    # so we just use the test_loader which returns the whole dataset if we configure it right.\n',
                '    # We will use the raw dataset class instead of the split loader to evaluate the entire BUSBRA.\n',
                '    from datasets.medical_dataset import MedicalImageMaskDataset, get_medical_transforms\n',
                '    from torch.utils.data import DataLoader\n',
                '    \n',
                '    _, transform = get_medical_transforms(224)\n',
                '    busbra_dataset = MedicalImageMaskDataset("data/busbra_dataset", transform=transform)\n',
                '    busbra_loader = DataLoader(busbra_dataset, batch_size=16, shuffle=False, num_workers=2)\n',
                '    \n',
                '    # BUSBRA provides binary ground truth (0=background, 1=tumor).\n',
                '    # Our model predicts 3 classes (0=background, 1=benign, 2=malignant).\n',
                '    # We must evaluate it as a 2-class problem by mapping all tumor predictions to 1.\n',
                '    accumulator = SegmentationMetricAccumulator(num_classes=2)\n',
                '    \n',
                '    print("Running Zero-Shot Inference on BUSBRA...")\n',
                '    with torch.no_grad():\n',
                '        for images, targets in busbra_loader:\n',
                '            images, targets = images.cuda(), targets.cuda()\n',
                '            with torch.amp.autocast("cuda"):\n',
                '                logits = model(images)\n',
                '            preds = logits.argmax(dim=1)\n',
                '            \n',
                '            # Map benign (1) and malignant (2) into a single \"tumor\" class (1) for zero-shot binary eval\n',
                '            preds = (preds > 0).long()\n',
                '            \n',
                '            accumulator.update(preds, targets)\n',
                '            \n',
                '    metrics = accumulator.compute()\n',
                '    print("\\n=== FINAL ZERO-SHOT METRICS ===")\n',
                '    for k, v in metrics.items():\n',
                '        print(f"{k}: {v:.4f}")\n',
                '        \n',
                '    os.makedirs("zero_shot_results", exist_ok=True)\n',
                '    with open("zero_shot_results/zero_shot_metrics.json", "w") as f:\n',
                '        json.dump(metrics, f, indent=4)\n',
                '    print("\\nResults saved to zero_shot_results/zero_shot_metrics.json")'
            ]
        }
    ],
    'metadata': {
        'kernelspec': {
            'display_name': 'Python 3',
            'language': 'python',
            'name': 'python3'
        },
        'language_info': {
            'name': 'python',
            'version': '3.10.12'
        }
    },
    'nbformat': 4,
    'nbformat_minor': 4
}

with open('Phase9_Standard_MLP_Swin_MoE.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)
